import os
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from backend.app.database.session import get_db
from backend.app.database.models import User, Incident, Evidence, Prediction, Report
from backend.app.auth.dependencies import get_current_user
from backend.app.schemas.report import ReportResponse
from backend.app.reports.report_generator import get_report_generator

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("", response_model=List[ReportResponse])
def list_reports(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """List all reports generated by or available to the current user."""
    if current_user.role == "ADMIN":
        reports = db.query(Report).order_by(Report.generated_at.desc()).all()
    else:
        reports = db.query(Report).filter(Report.user_id == current_user.id).order_by(Report.generated_at.desc()).all()

    return [
        ReportResponse(
            id=r.id,
            incident_id=r.incident_id,
            user_id=r.user_id,
            report_code=r.report_code,
            pdf_path=r.pdf_path,
            summary_json=r.summary_json,
            generated_at=r.generated_at,
            download_url=f"/api/reports/{r.id}/download"
        )
        for r in reports
    ]

@router.post("/generate/{incident_id}", response_model=ReportResponse)
def generate_report_for_incident(
    incident_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Compiles a fresh PDF report artifact from the current database state of the incident."""
    query = db.query(Incident).filter(Incident.id == incident_id)
    if current_user.role != "ADMIN":
        query = query.filter(Incident.user_id == current_user.id)
    incident = query.first()

    if not incident:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Incident not found"
        )

    evidence_records = db.query(Evidence).filter(Evidence.incident_id == incident.id).all()
    evidence_payload = []
    for ev in evidence_records:
        pred = db.query(Prediction).filter(Prediction.evidence_id == ev.id).first()
        evidence_payload.append({
            "evidence_type": ev.evidence_type,
            "detected_language": ev.detected_language,
            "edited_text": ev.edited_text,
            "predicted_class": pred.predicted_class if pred else "Unclassified",
            "confidence": pred.confidence if pred else 0.0,
            "explanation": pred.explainability_json if pred else "Evidence cataloged."
        })

    pdf_data = {
        "incident_code": incident.incident_code,
        "platform": incident.platform,
        "primary_category": incident.primary_category or "Cyberbullying",
        "confidence": incident.confidence,
        "severity": incident.severity,
        "created_at": incident.created_at.strftime("%Y-%m-%d %H:%M:%S UTC"),
        "evidence_items": evidence_payload
    }

    report_gen = get_report_generator()
    pdf_path = report_gen.generate_pdf(pdf_data)

    report_code = f"REP-{incident.incident_code.replace('CB-', '')}"
    existing_rep = db.query(Report).filter(Report.incident_id == incident.id).first()
    if existing_rep:
        existing_rep.pdf_path = pdf_path
        existing_rep.summary_json = pdf_data
        db.commit()
        report_record = existing_rep
    else:
        report_record = Report(
            incident_id=incident.id,
            user_id=current_user.id,
            report_code=report_code,
            pdf_path=pdf_path,
            summary_json=pdf_data
        )
        db.add(report_record)
        db.commit()
        db.refresh(report_record)

    return ReportResponse(
        id=report_record.id,
        incident_id=report_record.incident_id,
        user_id=report_record.user_id,
        report_code=report_record.report_code,
        pdf_path=report_record.pdf_path,
        summary_json=report_record.summary_json,
        generated_at=report_record.generated_at,
        download_url=f"/api/reports/{report_record.id}/download"
    )

@router.get("/{report_id}/download")
def download_report(
    report_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Download the actual PDF file."""
    query = db.query(Report).filter(Report.id == report_id)
    if current_user.role != "ADMIN":
        query = query.filter(Report.user_id == current_user.id)
    report = query.first()

    if not report or not os.path.exists(report.pdf_path):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report PDF file not found on server"
        )

    filename = os.path.basename(report.pdf_path)
    return FileResponse(
        path=report.pdf_path,
        media_type="application/pdf",
        filename=filename
    )
